import src.webs_scrapers as scrapers

scrapers_ = {
    "AlaantkoweBlw": scrapers.AlaantkoweblwScraper,
    "Aga ma Smaka": scrapers.AgaMaSmakaScraper,
    "Be Fit Be Strong": scrapers.BeFitBeStrongScraper,
    "Ekspresja Smaku": scrapers.EkspresjaSmakuScraper,
    "erVegan": scrapers.ErVeganScraper,
    "FlyMeToTheSpoon": scrapers.FlyMeToTheSpoonScraper,
    "Healthy Living James": scrapers.HealthyLivingJamesScraper,
    "Healthy Omnomnom": scrapers.HealthyOmnomnomScraper,
    "Jadłonomia": scrapers.JadlonomiaScraper,
    "Little Hungry Lady": scrapers.LittleHungryLadyScraper,
    "Madeleine Olivia": scrapers.MadeleineOliviaScraper,
    "Mina Rome": scrapers.MinaRomeScraper,
    "Olga Smile": scrapers.OlgaSmileScraper,
    "Oh My Veggies": scrapers.OhMyVeggiesScraper,
    "Rozkoszny": scrapers.RozkosznyScraper,
    "Salaterka": scrapers.SalaterkaScraper,
    "true taste hunters": scrapers.TrueTasteHuntersScraper,
    "Upieczona": scrapers.UpieczonaScraper,
    "Warzywizm": scrapers.WarzywizmScraper,
    "wegan nerd": scrapers.WegannerdScraper,
    "wegAnka": scrapers.WegankaScraper,
    "Weganon": scrapers.WeganonScraper,
    "Wegepedia": scrapers.WegepediaScraper,
    "Wilkuchnia": scrapers.WilkuchniaScraper,
    "Vegan Richa": scrapers.VeganRichaScraper,
    "veganbanda": scrapers.VeganbandaScraper,
    "vegenerat-biegowy": scrapers.VegeneratBiegowyScraper,
    "VegeMi": scrapers.VegeMiScraper,
    "Zen w kuchni": scrapers.ZenWKuchniScraper,
    "zielony środek": scrapers.ZielonySrodekScraper,
}
