from src.webs_scrapers import all_scrapers

scrapers_ = {
    "AlaantkoweBlw": all_scrapers.AlaantkoweblwScraper,
    "Aga ma Smaka": all_scrapers.AgaMaSmakaScraper,
    "Be Fit Be Strong": all_scrapers.BeFitBeStrongScraper,
    "erVegan": all_scrapers.ErVeganScraper,
    "FlyMeToTheSpoon": all_scrapers.FlyMeToTheSpoonScraper,
    "Healthy Living James": all_scrapers.HealthyLivingJamesScraper,
    "Healthy Omnomnom": all_scrapers.HealthyOmnomnomScraper,
    "Jadłonomia": all_scrapers.JadlonomiaScraper,
    "Little Hungry Lady": all_scrapers.LittleHungryLadyScraper,
    "Madeleine Olivia": all_scrapers.MadeleineOliviaScraper,
    "Olga Smile": all_scrapers.OlgaSmileScraper,
    "Oh My Veggies": all_scrapers.OhMyVeggiesScraper,
    "Upieczona": all_scrapers.UpieczonaScraper,
    "Warzywizm": all_scrapers.WarzywizmScraper,
    "weganbanda": all_scrapers.WeganbandaScraper,
    "Weganon": all_scrapers.WeganonScraper,
    "Wegepedia": all_scrapers.WegepediaScraper,
    "Wilkuchnia": all_scrapers.WilkuchniaScraper,
    "vegenerat-biegowy": all_scrapers.VegeneratBiegowyScraper,
    "VegeMi": all_scrapers.VegeMiScraper,
    "Zen w kuchni": all_scrapers.ZenWKuchniScraper,
    "zielony środek": all_scrapers.ZielonySrodekScraper,
}
